### PR TITLE
Add new project: Packaging the HEP simulation stack on conda-forge

### PR DESCRIPTION
**Pull request by Kwaizer**

### CODE REVIEW

**Comment by Kwaizer** [comment]
@matthewfeickert I created a PR to add this project to the database. Can you please check it when you'll have time. I'm not sure if `description` and `experiments` are specified correctly.

**Comment by matthewfeickert** [comment]
@Kwaizer Sorry, but why is this PR needed? PR https://github.com/research-software-collaborations/project_database/pull/62 added it when I created the project. This project database is for projects to get added to the pool, not for projects that are already started. I think we can close this PR.

**Comment by Kwaizer** [comment]
@matthewfeickert oh, I got it. I've just seen this as an onboarding step [here](https://iris-hep.org/docs/fellows_onboarding) for `IRIS-HEP Web Site` and thought that this also needs to be done now. I close the PR.

**Comment by matthewfeickert** [comment]
> oh, I got it. I've just seen this as an onboarding step [here](https://iris-hep.org/docs/fellows_onboarding) for `IRIS-HEP Web Site` and thought that this also needs to be done now.

@Kwaizer The link tells you to update the project status, not create a new one. c.f. https://github.com/research-software-collaborations/project_database/blob/main/README.md#changing-the-status-of-your-project

So you should update

https://github.com/research-software-collaborations/project_database/blob/35ec697005e999a18ff4b8b460346ecacc52d273/projects/conda-forge-simulation-stack.yml#L13-L14

**Pull request closed without merging**
